function p_out = rem_parameters(p_in); persistent parameters;

    if(nargin == 1)
        parameters = set_or_default(p_in, defaults());
    end

    if(nargin == 0 && isempty(parameters))
        parameters = set_or_default(struct(), defaults());
    end

    p_out = parameters;
end

function d = defaults()
    d = struct(...
         'epsilon' ,.001    ...
        ,'gamma'   , 0.9    ...
        ,'steps'   , 2      ...
        ,'samples' , 100    ...
        ,'max_hist', 20     ...
        ,'pop_size', 37     ...
        ,'epi_size', 10     ...
        ,'epi_step', 1      ...
        ,'N'       , 30     ... %50
        ,'M'       , 90     ...
        ,'T'       , 01     ... %04
        ,'W'       , 04     ...
        ,'v_feats' , 1      ...
        ,'kernel'  , k_dot()...
    );
end