function p_out = rem_parameters(p_in, force); persistent parameters;

    if((nargin == 2 && force) || (nargin == 1 && isempty(parameters)))
        parameters = fill_default_params(p_in, default_params());
    elseif(nargin == 0 && isempty(parameters))
        parameters = fill_default_params(struct(), default_params());
    end

    p_out = parameters;

end

function d = default_params()
    d = struct(...
         'rand_ns' , 10     ...
        ,'epsilon' ,.001    ...
        ,'gamma'   , 0.9    ...
        ,'steps'   ,  2    ...
        ,'samples' , 100    ...
        ,'max_hist',  20    ...
        ,'pop_size',  37    ...
        ,'epi_size',  10    ...
        ,'epi_step',   1    ...
        ,'N'       ,  30    ... %50
        ,'M'       ,  90    ...
        ,'T'       ,  01    ... %04
        ,'W'       ,  04    ...
        ,'v_basis' , '1a'   ...
        ,'kernel'  , k_dot()...
    );
end

function params = fill_default_params(params,defaults)

    % Get default field names.
    defaultfields = fieldnames(defaults);

    % Step over all fields in the defaults structure.
    for i=1:length(defaultfields)
        if ~isfield(params,defaultfields{i})
            params.(defaultfields{i}) = defaults.(defaultfields{i});
        end
    end

end